package com.example.tugoflogic.models

enum class ESocket(val value: String) {
    SHOW_MAINCLAIM("SHOW_MAINCLAIM"),
    VOTE_MAINCLAIM1("VOTE_MAINCLAIM1"),
    NEW_VOTE_MAINCLAIM1_COMING("NEW_VOTE_MAINCLAIM1_COMING"),
    VOTE_MAINCLAIM2("VOTE_MAINCLAIM2"),
    NEW_VOTE_MAINCLAIM2_COMING("NEW_VOTE_MAINCLAIM2_COMING"),
    RIP_COMING("RIP_COMING"),
    DEBATE_RIP("DEBATE_RIP"),
    VOTE_RIP("VOTE_RIP"),
    VOTE_RIP_COMING("VOTE_RIP_COMING")
}